cmake_minimum_required(VERSION 3.25 FATAL_ERROR)

macro(parse_package_info FILEPATH)
    file(READ ${FILEPATH} PACKAGE_INFO_FILE)
    string(JSON PACKAGE_NAME GET ${PACKAGE_INFO_FILE} name)
    string(JSON PACKAGE_DISPLAY_NAME GET ${PACKAGE_INFO_FILE} displayname)
    string(JSON PACKAGE_VERSION GET ${PACKAGE_INFO_FILE} version)
    string(JSON PACKAGE_AUTHOR GET ${PACKAGE_INFO_FILE} author)
    string(JSON PACKAGE_DESCRIPTION GET ${PACKAGE_INFO_FILE} description)
    string(JSON PACKAGE_WEBSITE GET ${PACKAGE_INFO_FILE} website)
    string(JSON PACKAGE_REVERSE_DOMAIN GET ${PACKAGE_INFO_FILE} package_extra reverse_domain)
    string(JSON PACKAGE_COPYRIGHT GET ${PACKAGE_INFO_FILE} package_extra copyright)
    string(REPLACE "(c)" © PACKAGE_COPYRIGHT ${PACKAGE_COPYRIGHT})
    unset(PACKAGE_INFO_FILE)
    set(PACKAGE_FILELIST "")
endmacro()
